version: "3.9"

services:
  feature-store:
    build: ./feature_store
    depends_on:
      minio-init:
        condition: service_completed_successfully
    volumes:
      - ./feature_store/feast_repo:/app/feast_repo
    environment:
      # MinIO(S3)에서 raw 읽고 processed/feast에 씀
      RAW_S3_PREFIX: s3://ml-data/raw
      OUT_S3_PREFIX: s3://ml-data/processed
      FEAST_REGISTRY_S3: s3://ml-data/feast/registry.db

      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data

  # MinIO에 버킷 생성 (1회성)
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      mc mb -p local/mlflow || true;
      mc mb -p local/ml-data || true;
      exit 0;
      "
    restart: "no"

  # PostgreSQL (MLflow Backend Store)
  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    restart: always
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MLflow Tracking Server
  mlflow:
    build: ./mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio-init
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root s3://mlflow
      --serve-artifacts
      --allowed-hosts '*'

  training:
    build: ./training
    depends_on:
      - feature-store
      - mlflow
    environment:
      FEAST_REPO_PATH: /app/feast_repo
      MLFLOW_TRACKING_URI: http://mlflow:5000

      # labels도 S3에서 읽게 변경
      LABEL_URI: s3://ml-data/raw/application_train.csv

      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - ./training:/app
      - ./feature_store/feast_repo:/app/feast_repo

  inference:
    build: ./inference
    container_name: inference
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000

volumes:
  minio_data:
  postgres_data:
