version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ 기본 포트
      - "15672:15672" # RabbitMQ 관리 UI 포트

  feature-store:
    build:
      context: .
      dockerfile: ./feature_store/Dockerfile
    container_name: feature-store
    depends_on:
      minio-init:
        condition: service_completed_successfully # MinIO 초기화 완료 후 시작
    volumes:
      - ./feature_store/feast_repo:/app/feast_repo
    environment:
      RAW_S3_PREFIX: s3://ml-data/raw # 원시 데이터 위치
      PROCESSED_S3_PREFIX: s3://ml-data/processed # 가공된 데이터 위치
      FEAST_REGISTRY_S3: s3://ml-data/feast/registry.db # Feature Registry 위치

      # S3 접속 정보
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000

  # MinIO (S3 호환 오브젝트 스토리지)
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001" # 콘솔 UI 활성화
    ports:
      - "9000:9000" # S3 API 통신용(SDK, CLI 등이 접근하는 포트)
      - "9001:9001" # 브라우저 접속용 콘솔 UI 포트
    environment:
      MINIO_ROOT_USER: minioadmin # 관리자 로그인 아이디 (편의상 기본값 사본)
      MINIO_ROOT_PASSWORD: minioadmin123 # 관리자 로그인 비밀번호 (편의상 기본값 사본)
    volumes:
      - minio_data:/data # 컨테이너가 종료되어도 데이터가 유지되도록 볼륨 마운트

  # MinIO 서버가 시작된 후에 버킷을 생성하는 1회성 초기화 작업
  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - minio # MinIO가 먼저 시작되어야 함
    entrypoint: > # mc 명령어로 MinIO에 접속하여 초기 세팅 수행
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      mc mb -p local/mlflow || true;
      mc mb -p local/ml-data || true;
      mc mb -p local/models || true;
      mc mb -p local/inference-logs || true;
      exit 0;
      "
    restart: "no"

  # PostgreSQL (MLflow Backend Store)
  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    restart: always
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MLflow Tracking Server
  mlflow:
    build:
      context: .
      dockerfile: ./mlflow/Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres # Backend Store
      - minio-init # S3 Storage
    environment:
      # MLflow는 클라이언트들을 대신해 MinIO에 접속하므로 MinIO 접속 정보 필요
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root s3://mlflow
      --serve-artifacts

  training:
    build:
      context: .
      dockerfile: ./training/Dockerfile
    container_name: training
    depends_on:
      - feature-store
      - mlflow
    environment:
      FEAST_REPO_PATH: /app/feast_repo
      MLFLOW_TRACKING_URI: http://mlflow:5000

      # labels도 S3에서 읽게 변경
      LABEL_URI: s3://ml-data/raw/application_train.csv

      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000

  triton:
    build:
      context: .
      dockerfile: ./triton/Dockerfile
    container_name: triton
    ports:
      - "8000:8000" # Triton HTTP
      - "8001:8001" # Triton gRPC
      - "8002:8002" # Triton Metrics
    depends_on:
      - mlflow
      - training
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      
  inference:
    build:
      context: .
      dockerfile: ./inference/Dockerfile
    container_name: inference
    ports:
      - "8080:8080" # FastAPI
    depends_on:
      - mlflow
      - rabbitmq
    environment:
      TRITON_HOST: triton
      TRITON_PORT: "8000"
      MODEL_NAME: HomeCreditDefaultModel

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

  log-worker:
    build:
      context: .
      dockerfile: ./log_worker/Dockerfile
    container_name: log-worker
    depends_on:
      - rabbitmq
      - minio
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: http://minio:9000
      S3_BUCKET_NAME: inference-logs

volumes:
  minio_data:
  postgres_data:
