# -- helm/templates/hpa.yaml

{{- if .Values.triton.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: triton-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: triton
  minReplicas: {{ .Values.triton.hpa.minReplicas }}
  maxReplicas: {{ .Values.triton.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.triton.hpa.targetCPUUtilizationPercentage }}
{{- end }}

---

{{- if .Values.inference.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inference-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inference
  minReplicas: {{ .Values.inference.hpa.minReplicas }}
  maxReplicas: {{ .Values.inference.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.inference.hpa.targetCPUUtilizationPercentage }}
{{- end }}
