apiVersion: v1
kind: Service
metadata:
  name: inference
spec:
  selector: {app: inference}
  type: NodePort
  ports:
    - name: fastapi
      port: 8080
      targetPort: 8080
      nodePort: 30080
