apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 1
  selector:
    matchLabels: {app: inference}
  template:
    metadata:
      labels: {app: inference}
    spec:
      containers:
        - name: inference
          image: jpyo0803/inference:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # FastAPI
          env:
            - name: TRITON_HOST
              value: "triton"
            - name: TRITON_PORT
              value: "8000"
            - name: MODEL_NAME
              value: "HomeCreditDefaultModel"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
