apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels: {app: mlflow}
  template:
    metadata:
      labels: {app: mlflow}
    spec:
      containers:
        - name: mlflow
          image: mlflow-custom:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom: {secretKeyRef: {name: minio-credentials, key: AWS_ACCESS_KEY_ID}}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom: {secretKeyRef: {name: minio-credentials, key: AWS_SECRET_ACCESS_KEY}}
            - name: AWS_DEFAULT_REGION
              valueFrom: {secretKeyRef: {name: minio-credentials, key: AWS_DEFAULT_REGION}}
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom: {secretKeyRef: {name: minio-credentials, key: MLFLOW_S3_ENDPOINT_URL}}
          command: ["mlflow"]
          args:
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --backend-store-uri
            - postgresql://mlflow:mlflow@postgres:5432/mlflow
            - --default-artifact-root
            - s3://mlflow
            - --serve-artifacts
            - --allowed-hosts
            - "*"
