apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
spec:
  replicas: 1
  selector:
    matchLabels: {app: triton}
  template:
    metadata:
      labels: {app: triton}
    spec:
      containers:
        - name: triton
          image: jpyo0803/triton:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000 # HTTP
            - containerPort: 8001 # gRPC
            - containerPort: 8002 # Metrics
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin123"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio:9000"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"