apiVersion: v1
kind: Service
metadata:
  name: triton
spec:
  selector: {app: triton}
  type: NodePort
  ports:
    - name: triton-http
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: triton-grpc
      port: 8001
      targetPort: 8001
      nodePort: 30001
    - name: triton-metrics
      port: 8002
      targetPort: 8002
      nodePort: 30002