# -- helm/templates/apps/feast.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-server
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-server
  template:
    metadata:
      labels:
        app: feast-server
    spec:
      initContainers:
      # 버킷 생성용 Init Container
      - name: wait-for-minio
        image: {{ .Values.images.minioMc | quote }}
        command:
        - /bin/sh
        - -c
        - |
          echo "Connecting to MinIO..."
          # MinIO 접속 시도 (성공할 때까지 반복)
          until mc alias set myminio $AWS_ENDPOINT_URL $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY; do
            echo "Waiting for MinIO..."
            sleep 2
          done
          
          echo "MinIO connected. Creating buckets..."
          # 버킷 생성 (이미 존재하면 --ignore-existing 옵션 덕분에 에러 없이 넘어감)
          mc mb myminio/ml-data --ignore-existing
          
          echo "Bucket 'ml-data' is ready!"
        env:
        # 공통 MinIO 환경 변수 주입
        {{- include "common.env.minio" . | nindent 8 }}
      containers:
      - name: feast
        image: {{ .Values.images.featureStore | quote }}
        workingDir: /app/feast_repo
        command: ["feast", "serve"]
        args: ["--host", "0.0.0.0", "--port", "{{ .Values.featureStore.registryPort }}"]
        env:
        - name: FEAST_REPO_PATH
          value : "/app/feast_repo"
        # 공통 MinIO 환경 변수 주입
        {{- include "common.env.minio" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.featureStore.registryPort }}
        volumeMounts:
        - name: feast-repo-config
          mountPath: /app/feast_repo/feature_store.yaml
          subPath: feature_store.yaml
        - name: feast-data
          mountPath: /app/feast_repo/data
      volumes:
      - name: feast-repo-config
        configMap:
          name: feast-repo-config
      - name: feast-data 
        persistentVolumeClaim:
          claimName: feast-registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: feast
spec:
  selector:
    app: feast-server
  ports:
  - port: {{ .Values.featureStore.registryPort }}
    targetPort: {{ .Values.featureStore.registryPort }}