# -- helm/templates/apps/inference.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  namespace: {{ .Values.global.namespace }}
spec:
  # replicas: 1
  # 포드 수는 hpa.yaml에서 정의한 minReplicas 및 maxReplicas에 의해 관리됩니다.
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: {{ .Values.images.inference | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.inference.servicePort }}
        env:
        - name: TRITON_HOST
          value: "triton"
        - name: TRITON_PORT
          value: "8000"
        - name: MODEL_NAME
          value: {{ .Values.triton.modelName | quote }}
        - name: PYTHONUNBUFFERED
          value: "1"
        # 공통 RabbitMQ 환경 변수 주입
        {{- include "common.env.rabbitmq" . | nindent 8 }}
        resources:
          requests:
            cpu: "500m"     # 이 값을 기준으로 70%(HPA 설정값)를 계산
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: inference
  namespace: {{ .Values.global.namespace }}
  labels:
    app: inference # ServiceMonitor가 이 라벨을 사용하여 서비스를 찾음
spec:
  type: NodePort
  selector:
    app: inference
  ports:
  - name: http
    port: {{ .Values.inference.servicePort }}
    targetPort: {{ .Values.inference.servicePort }}
    nodePort: {{ .Values.inference.nodePort }} # 외부에서 접근할 포트
