# -- helm/templates/infrastructure/feast-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feast-registry-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.infrastructure.storageClass | quote}}
  resources:
    requests:
      storage: {{ .Values.featureStore.registryStorageSize | default "1Gi" }}
